apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: pod-reader
rules:
- apiGroups: ["","apps"] # "" indicates the core API group and apps
  resources: ["*"] #pods, sercvices and deployments too.
  verbs: ["get", "watch", "list"]